[phases.setup]
nixPkgs = ["nodejs_24", "pnpm"]

[phases.install]
cmds = ["corepack enable", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build:v3"]

[start]
cmd = "node apps/server/dist/index.js"
